#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: 1.0.{build}-{branch}

# caching
cache:
  - '%APPDATA%\stack -> *.yml'
  - '%APPDATA%\local\bin'

# branches to build
branches:
  only:
    - master
    - /^deploy-[0-9.]*$/
    - /^v[0-9.]*$/
  except:
    - /^devel-[0-9.]*$/
    - /^test-[0-9.]*$/
    - gh-pages

# scripts that run after cloning repository
install:
  # by default, all script lines are interpreted as batch
  - cmd: >-
      curl -ostack.zip -L --insecure http://www.stackage.org/stack/windows-i386 &&
      7z x stack.zip stack.exe

environment:
  matrix:
    - build: stack
      args:
    - build: stack
      args: --resolver lts-3
    - build: stack
      args: --resolver lts-6
    - build: stack
      args: --resolver lts-7
    - build: stack
      args: --resolver nightly
    - build: style
      args:

matrix:
  fast_finish: true
  allow_failures:
    - build: stack
      args: --resolver nightly

#---------------------------------#
#       build configuration       #
#---------------------------------#

# scripts to run before build
before_build:
  - SET PATH=%PATH%;C:\Users\appveyor\AppData\Roaming\local\bin\
  - cmd: >-
      if "%build%"=="stack" (
      ECHO "STACK/BEFORE_BUILD" &&
      stack --no-terminal --install-ghc %args% test --bench --only-dependencies > nul 2>&1
      ) ELSE (
      ECHO "OTHER/BEFORE_BUILD" &&
      stack --no-terminal --install-ghc %args% install hlint > nul 2>&1
      )

# to run your custom scripts instead of automatic MSBuild
build_script:
  - cmd: >-
      IF "%build%"=="stack" (
      ECHO "STACK/BUILD" &&
      stack --no-terminal %args% test --bench --no-run-benchmarks --haddock --no-haddock-deps
      ) ELSE (
      ECHO "OTHER/BUILD" &&
      hlint src/ test/ --cpp-simple --hint=HLint.hs &&
      stack --no-terminal build --ghc-options -Wall
      )
